### ISSUE TITLE
请问怎么使用啊

### ISSUE THREAD

**Issue by TheGayhub** [kdxcxs/wqDownloader#1]

**Comment by kdxcxs** [comment]
1. 下载Fiddler,就是那个代理软件,在里面找到AutoResponder,添加一条规则,第一行就填```EXACT:https://lib-nuanxin.wqxuetang.com/static/read/js/read.v5.3.1.722eb.js```,第二行就填克隆我仓库后里面那个```read.v5.3.1.722eb.js```的绝对地址.

2. 把浏览器的代理设置成Fiddler的代理地址,运行仓库里面的```save_img.py```,在浏览器里面打开想要下载的书的浏览地址(就是能看到书正文,url是```https://lib-nuanxin.wqxuetang.com/read/pdf/```开头的那种).

3. 网页一打开下载应该就开始了.下载过程中会自动翻页,有可能还会刷新(而且几率很大,不知道是我的网络环境问题还是服务器的限制).下载完成后网页会有alert提示.在```save_img.py```的文件夹下面就会多一个```Download```文件夹,里面是下载的文件.
